### PR TITLE
Update target to .NET standard 2.1

### PR DESCRIPTION
**Pull request by vlnevyhosteny**
# This pull request includes updates to the library and test project:

- Library Update: The library has been migrated to .NET Standard 2.1, enabling cross-platform compatibility on Mac, mobile, and other platforms. 
- Test Project Update: The test project has been upgraded to .NET 7.0, aligning it with the latest .NET framework version. 
- Dependency Updates: All dependencies have been updated to their latest versions.

### CODE REVIEW

**Review by ViolanteCodes — CHANGES_REQUESTED** [review]
Thanks for your patience as we decided how to proceed - we've decided to go with the major versioning change and making the old version obsolete, so as to avoid supporting two separate SDKs.

As such, can you also also bump the version in the readme.md and the .proj file: https://github.com/ButterCMS/buttercms-csharp/blob/master/ButterCMS/ButterCMS.csproj? and it looks like there are some deprecated tests that need to be upgraded: https://app.clickup.com/t/861n7ae7q - can we have these upgraded? Please let me know what you need from me to make that happen.

Thank you!

**Comment by vlnevyhosteny** [comment]
> Thanks for your patience as we decided how to proceed - we've decided to go with the major versioning change and making the old version obsolete, so as to avoid supporting two separate SDKs.
> 
> As such, can you also also bump the version in the readme.md and the .proj file: https://github.com/ButterCMS/buttercms-csharp/blob/master/ButterCMS/ButterCMS.csproj? and it looks like there are some deprecated tests that need to be upgraded: https://app.clickup.com/t/861n7ae7q - can we have these upgraded? Please let me know what you need from me to make that happen.
> 
> Thank you!

Version bumped in 63695f617e88cdf41f2b805e88c9b79c501f37c1.

**Comment by ViolanteCodes** [comment]
> > Thanks for your patience as we decided how to proceed - we've decided to go with the major versioning change and making the old version obsolete, so as to avoid supporting two separate SDKs.
> > As such, can you also also bump the version in the readme.md and the .proj file: https://github.com/ButterCMS/buttercms-csharp/blob/master/ButterCMS/ButterCMS.csproj? and it looks like there are some deprecated tests that need to be upgraded: https://app.clickup.com/t/861n7ae7q - can we have these upgraded? Please let me know what you need from me to make that happen.
> > Thank you!
> 
> Version bumped in [63695f6](https://github.com/ButterCMS/buttercms-csharp/commit/63695f617e88cdf41f2b805e88c9b79c501f37c1).

awesome, thank you - i'll wait to review until the new tests are done, so that they can go with the new version

**Comment by vlnevyhosteny** [comment]
PR with tests: https://github.com/ButterCMS/buttercms-csharp/pull/38

**Pull request merged**
